kind: Deployment
apiVersion: apps/v1
metadata:
  name: loyalty-program
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loyalty-program
  template:
    metadata:
      labels:
        app: loyalty-program
    spec:
      containers:
        - name: loyalty-program
          image: loyalty-program
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80  
---
kind: Service
apiVersion: v1
metadata:
  name: loyalty-program
spec:
  type: LoadBalancer
  ports:
    - name: loyalty-program
      port: 8083
      targetPort: 80
  selector:
    app: loyalty-program