kind: Deployment
apiVersion: apps/v1
metadata:
  name: special-offers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: special-offers
  template:
    metadata:
      labels:
        app: special-offers
    spec:
      containers:
        - name: special-offers
          image: special-offers
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80  
---
kind: Service
apiVersion: v1
metadata:
  name: special-offers
spec:
  type: LoadBalancer
  ports:
    - name: special-offers
      port: 8082
      targetPort: 80
  selector:
    app: special-offers
      